# Generated by Django 6.0 on 2025-12-23 10:32

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='movie_app.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('1080p Ultra', '1080p Ultra')], default='1080p', max_length=32),
        ),
        migrations.AlterField(
            model_name='movielanguages',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_videos', to='movie_app.movie'),
        ),
    ]
