# Generated by Django 6.0 on 2025-12-25 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_userprofile_avatar_alter_review_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='actor_movie', to='movie_app.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='movie_country', to='movie_app.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='director_movie', to='movie_app.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movie_genre', to='movie_app.genre'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_movie', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='movie_app.review'),
        ),
    ]
